In [43]:
import numpy as np

details = [1,2,3],[4,-1,6],[3,99,2]
sales = np.array(details)

#print(sales)
sales.min()
#print(sales.shape)

-1

In [23]:
sales.ndim

2

In [25]:
sales.T

array([[ 1,  4,  3],
       [ 2, -1,  0],
       [ 3,  6,  2]])

In [27]:
sales.sum()

20

In [33]:
sales.max()

99

In [37]:
sales.shape

(3, 3)

In [45]:
sales.reshape(9,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [-1],
       [ 6],
       [ 3],
       [99],
       [ 2]])

In [49]:
sales2 = np.array([[1],[2],[3]])
sales.dot(sales2)

array([[ 14],
       [ 20],
       [207]])

In [53]:
np.count_nonzero(sales)

9

In [59]:
details = [1,0,0],[4,-1,6],[3,-5,2]
s1 = np.array(details)
np.count_nonzero(s1)

7

In [79]:
s1.sort()

In [81]:
s1

array([[ 0,  0,  1],
       [-1,  4,  6],
       [-5,  2,  3]])

In [75]:
s1.flatten()

array([ 0,  0,  1, -1,  4,  6, -5,  2,  3])

In [77]:
s1

array([[ 0,  0,  1],
       [-1,  4,  6],
       [-5,  2,  3]])

In [83]:
s1+3

array([[ 3,  3,  4],
       [ 2,  7,  9],
       [-2,  5,  6]])

In [85]:
s1

array([[ 0,  0,  1],
       [-1,  4,  6],
       [-5,  2,  3]])

In [87]:
s1.diagonal()

array([0, 4, 3])

In [89]:
s1.trace()

7