In [1]:
import numpy as np

In [3]:
l1 = [1,4,3,4,2]
arr1 = np.array(l1)

In [9]:
arr1

array([1, 4, 3, 4, 2])

In [43]:
type(arr1)

numpy.ndarray

In [13]:
arr1.shape

(5,)

In [15]:
arr1.ndim

1

In [19]:
arr1.size

5

In [11]:
arr2 = np.array([[1,4,2],
                 [2,4,1],
                 [5,6,3]])
arr2

array([[1, 4, 2],
       [2, 4, 1],
       [5, 6, 3]])

In [21]:
arr2.shape

(3, 3)

In [23]:
arr2.ndim

2

In [31]:
arr2.size

9

In [125]:
arr3 = np.array([[[1,3], 
                  [2,2],
                  [1,1]],
                 
                  [[2,2],
                  [4,4],
                  [1,5]]])

In [127]:
arr3

array([[[1, 3],
        [2, 2],
        [1, 1]],

       [[2, 2],
        [4, 4],
        [1, 5]]])

In [129]:
arr3.shape

(2, 3, 2)

In [77]:
itr = range(0,10,2)
arr4 = np.fromiter(itr, float)

In [81]:
arr4

array([0., 2., 4., 6., 8.])

In [95]:
a5 = np.arange(0,16,3, dtype=np.float32)

TypeError: arange() got an unexpected keyword argument 'ndim'

In [93]:
a5

array([ 0.,  3.,  6.,  9., 12., 15.], dtype=float32)

In [101]:
a6 = np.linspace(1,20,20)

In [103]:
a6

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [147]:
a6 = np.arange(12)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [153]:
a6= a6.reshape(2,2,3)

In [163]:
a6

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [161]:
a6.flatten('F')

array([ 0,  6,  3,  9,  1,  7,  4, 10,  2,  8,  5, 11])

In [205]:
import pandas as pd
df = pd.read_csv('matches.csv', usecols = ["id", "player_of_match"])

In [221]:
df[["Id"]].sum()

Id    990787010
dtype: int64

In [193]:
df.index = range(1000, 3190, 2)

In [225]:
dd = pd.DataFrame({
    "Names":["Suresh", "Rajesh", "Ganesh"],
    "Age":[40,34,8]}
)


In [227]:
dd

Names  Age
0  Suresh   40
1  Rajesh   34
2  Ganesh    8

In [209]:
rename (columns = Dict)
rename (index = Dict)

df.columns = ["]
df.index = []
df.index = range


In [3]:
import numpy as np

In [33]:
aa = np.array([[[1,3,4,5,6,7,8],
                  [2,5,6,7,7,8,5]
              ],
                  [
                      [2,3,4,4,4,4,4],
                      [2,4,3,5,3,8,9]
                  ]
              ])

In [47]:
aa.shape

(2, 2, 7)

In [57]:
print(aa[0:1])

[[[1 3 4 5 6 7 8]
  [2 5 6 7 7 8 5]]]


In [59]:
import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

# Correction factors for each city
corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
#print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [61]:
print(corrections[:, np.newaxis])

[[ 1.5]
 [-0.5]
 [ 2. ]]


In [75]:
aa[np.array([1])]

array([[[2, 3, 4, 4, 4, 4, 4],
        [2, 4, 3, 5, 3, 8, 9]]])

In [71]:
aa

array([[[1, 3, 4, 5, 6, 7, 8],
        [2, 5, 6, 7, 7, 8, 5]],

       [[2, 3, 4, 4, 4, 4, 4],
        [2, 4, 3, 5, 3, 8, 9]]])

In [103]:
b = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9],
              [10, 11, 12]])

In [115]:
b[:,:,1]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [101]:
b[:,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [125]:
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(sumrow)
#print(b[sumrow%10==0])

[10  9 20]


In [145]:
import pandas as pd
d = pd.DataFrame({
                'test': [1,2,3,4],
                'test2': [5,6,7,8]})

In [153]:
d

test  test2
0     1      5
1     2      6
2     3      7
3     4      8